# -*- coding: utf-8 -*-
"""cnn_class_hparam_v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nimMYtcRSmwx3XUf8cLTJVxMRQgKbUPn

Okey, so this is the base file for my configs. Configs are where I store the hyperparameter values that I use in my experiment runs.

This hyperparameter setup is a model based on the hyperparameters from the model by:

*ML-innovative*

**author**: ?

Will be used mainly for my "cnn_classifier_model" with my "train_loop" code.

The parameters are devided into 3 categories and are:

1. Data hparams
*   window_size
*   overlap
*   batch_size
2. Model hparams
*   conv1_hidden_channels
*   conv2_hidden_channels
*   conv3_output-channels
*   conv1_kernel_size
*   conv2_kernel_size
*   conv3_kernel_size
*   conv1_stride
*   conv2_stride
*   conv3_stride
*   maxpool_ks
*   conv_dropout
*   class_dropout
*   linear1_hidden_size
*   activation_fn
3. Training hparams
*   learning_rate
*   num_epochs
*   beta
*   weight_decay
"""

# -----------------------------
# 1. DATA HYPERPARAMETERS
# -----------------------------
DATA_HPARAMS = {
    "window_size": 3.0,       # seconds
    "overlap": 0.5,           # 50% overlap
    "batch_size": 64,         # good default
}


# -----------------------------
# 2. MODEL HYPERPARAMETERS
# -----------------------------
MODEL_HPARAMS = {
    # Convolutional feature sizes
    "conv1_hidden_channels": 32,
    "conv2_hidden_channels": 64,
    "conv3_output_channels": 128,

    # Kernel sizes (temporal)
    "conv1_kernel_size": 7,
    "conv2_kernel_size": 5,
    "conv3_kernel_size": 3,

    # Strides for temporal downsampling
    "conv1_stride": 1,
    "conv2_stride": 1,
    "conv3_stride": 1,

    # Max pooling kernel size (temporal)
    "maxpool_ks": 2,

    # Regularization
    "conv_dropout": 0.2,       # dropout inside CNN
    "class_dropout": 0.3,      # dropout in classifier head

    # Dense layer size before final output
    "linear1_hidden_size": 128,

    # Activation
    "activation_fn": "relu",
}


# -----------------------------
# 3. TRAINING HYPERPARAMETERS
# -----------------------------
TRAINING_HPARAMS = {
    "learning_rate": 2e-4,        # stable LR for noisy biosignal CNNs
    "num_epochs": 50,             # baseline value; adjust later
    "betas": (0.5, 0.999),        # Adam betas (GAN-style stability)
    "weight_decay": 1e-4,         # light L2 regularization
}

