# -*- coding: utf-8 -*-
"""cnn_class_v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nk6FgqOuQ-RYg8t4E0wkZ2eQJ7dRNhr1
"""

import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

import numpy as np
import torch

from configs.cnn_class_hparam_v1 import DATA_HPARAMS, MODEL_HPARAMS, TRAINING_HPARAMS
from src.dataloading.splits import load_eeg_and_triggers, make_stratified_group_folds
from src.dataloading.dataloader import make_dataloaders
from src.models.cnn_classifier_model import GUTNet
from src.training.train_loop import train_GUTNet
from src.evaluation.evaluation import plot_losses_errors

def set_seed(seed: int) -> None:
    """Set all random seeds for reproducibility."""
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def get_device() -> torch.device:
    """Get the device to use for training."""
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

def create_experiment_dir(root: str = "results") -> Path:
    """Create a timestamped experiment directory."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    exp_dir = Path(root) / f"exp_{timestamp}"
    exp_dir.mkdir(parents=True, exist_ok=True)
    return exp_dir


def save_json(obj: Dict[str, Any], path: Path) -> None:
    with path.open("w") as f:
        json.dump(obj, f, indent=2)

# ------------------------------------------------------------------
# 4. MAIN PIPELINE
# ------------------------------------------------------------------

def main() -> None:
    # --------------------------------------------------------------
    # 4.1 Setup
    # --------------------------------------------------------------
    device = get_device()
    print(f"Using device: {device}")

    # Create result folder for this run
    exp_dir = create_experiment_dir(root="results")
    print(f"Saving results to: {exp_dir}")

    # Save the configs actually used in this run (for reproducibility)
    save_json(DATA_HPARAMS, exp_dir / "data_hparams.json")
    save_json(MODEL_HPARAMS, exp_dir / "model_hparams.json")
    save_json(TRAINING_HPARAMS, exp_dir / "training_hparams.json")

     # --------------------------------------------------------------
    # 4.2 Load and window the EEG data
    # --------------------------------------------------------------
    from google.colab import drive
    drive.mount('/content/drive')  #Remember to change this when you go over from colab to VSCode

    path = '/content/drive/MyDrive/fake_eeg_gut.mat'

    window_size = DATA_HPARAMS["window_size"]
    overlap     = DATA_HPARAMS["overlap"]
    eeg_file    = path
    print("here we gooo.. Let't try to load the data.")
    # EXPECTED: X: (n_windows, n_channels, n_time), y: (n_windows,), subjects: (n_windows,)
    X, y, subjects = load_eeg_and_triggers(
        eeg_file=eeg_file,
        window_size=window_size,
        overlap=overlap,
    )

    print(f"X shape: {X.shape}, y shape: {y.shape}, subjects shape: {subjects.shape}")
    print("phh it worked.. that is a miracle!")
    n_channels = X.shape[1]
    n_time     = X.shape[2]
    n_classes  = int(len(np.unique(y)))
    print(f"Detected: {n_channels} channels, {n_time} timepoints, {n_classes} classes")


    all_results = []

    # Make folds (by subject, stratified on y)
    folds = make_stratified_group_folds(
        X=X,
        y=y,
        groups=subjects,       # or 'subjects' if your arg is named that
        n_splits= 5,
        random_state=0,
    )

    print(folds.shape)

    # ----------------------------------------------------------
    # 4.5 Loop over folds
    # ----------------------------------------------------------
    for k in range(folds):  #in range(folds) might not be my best idea
        # Make train/test DataLoaders from this folds dict
        batch_size = DATA_HPARAMS["batch_size"]
        train_loader, test_loader = make_dataloaders(
            folds=folds,
            k=k,                # fold index
            batch_size=batch_size,
        )

        # ------------------------------------------------------
        # 4.6 Build model for this fold
        # ------------------------------------------------------

        model = GUTNet(**MODEL_HPARAMS) #this will very likely crash and burn hard...
        model.to(device)

        # ------------------------------------------------------
        # 4.7 Train model
        # ------------------------------------------------------

        model, train_losses, train_errors, test_losses, test_errors = train_GUTNet(
            model=model,
            train_loader=train_loader,
            test_loader=test_loader,
            training_hparams=TRAINING_HPARAMS,  #yeah I would be surprised if this works on the first try as well
            device=device,
        )


        try:
            plot_losses_errors(
                train_losses=train_losses,
                test_losses=test_losses,
                train_errors=train_errors,
                test_errors=test_errors):
              save_path = os.path.join(exp_dir, "loss_and_error.png")
              fig.savefig(save_path, dpi=300, bbox_inches="tight")
              plt.close(fig)   #still have some work to do here

              print(f"Saved to {save_path}")

        except Exception as e:
            print(f"plot_loss_and_error_curves failed (you can ignore this if not implemented yet): {e}")

        # Store result summary for seed/fold
        fold_summary = {
            "fold": k,
            "train_loss": train_losses[-1],
            "test_loss": test_losses[-1],
        }
        all_results.append(fold_summary)

# --------------------------------------------------------------
# 4.11 Save global summary
# --------------------------------------------------------------
print("\nDone! All results saved.")
print("wtf it actually worked... that is crazzzzy")


if __name__ == "__main__":
    main()