# -*- coding: utf-8 -*-
"""make_fake_data_v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5is2o0f31yIhPxSMQ22kdLBCmnFTQF8
"""

import numpy as np
from scipy.io import savemat
from pathlib import Path

def generate_fake_eeg_mat(
    out_path: str = "data/fake_eeg_gut.mat",
    seed: int = 99,
):
    """
    Generate synthetic EEG-like gut data and save as a .mat file.

    Saved variables
    ---------------
    data : np.ndarray
        Shape = (time, trial, electrode, participant)
        time       = 30000 (15 s * 2000 Hz)
        trial      = 9
        electrode  = 20
        participant= 5

    labels : np.ndarray
        Shape = (trial, participant)
        Values are 1, 2, or 4. Each participant has exactly
        three trials of each label (total 9).

    participant_ids : np.ndarray
        Shape = (participant,)
        Values are [1, 2, 3, 4, 5].
    """

    # ---- fixed experiment settings ----
    n_participants = 5
    n_trials = 9
    n_electrodes = 20
    fs = 2000               # Hz
    trial_length_sec = 15
    n_time = fs * trial_length_sec  # 30000

    # ---- reproducibility ----
    np.random.seed(seed)

    # ---- allocate data tensor ----
    # shape: [time, trial, electrode, participant]
    data = np.zeros((n_time, n_trials, n_electrodes, n_participants),
                    dtype=np.float32)

    # ---- create labels: 3x each of 1, 2, 4 per participant ----
    class_codes = np.array([1, 2, 4], dtype=np.int32)
    trials_per_class = 3

    labels = np.zeros((n_trials, n_participants), dtype=np.int32)

    for p in range(n_participants):
        # [1,1,1,2,2,2,4,4,4] then shuffle trial order
        labels_for_p = np.repeat(class_codes, trials_per_class)
        labels_for_p = np.random.permutation(labels_for_p)
        labels[:, p] = labels_for_p

    # ---- generate noise-only signals ----
    # Mostly Gaussian noise, with small variation between
    # participants and electrodes. A tiny slow drift is added
    # to loosely mimic low-frequency / 1/f-like components.

    base_sigma = 1.0  # overall noise scale

    time_axis = np.arange(n_time) / fs  # seconds, if needed

    for p in range(n_participants):
        # Participant-level scaling (e.g. different skin/impedance)
        participant_gain = np.random.normal(loc=1.0, scale=0.15)

        for ch in range(n_electrodes):
            # Electrode-level scaling (slightly different noise level)
            electrode_gain = np.random.normal(loc=1.0, scale=0.10)

            # ---- Gaussian noise component ----
            gaussian_noise = np.random.randn(n_time, n_trials)

            # ---- slow drift component (very small) ----
            # Make a slow-varying signal by cumulative sum and smoothing-scale.
            drift = np.cumsum(np.random.randn(n_time)) / 500.0
            drift = drift[:, None]  # (time, 1), broadcast over trials

            # ---- occasional "motion artifact" spikes (rare, random) ----
            spike_mask = np.random.rand(n_time, n_trials) < 0.0005  # very sparse
            spikes = spike_mask * np.random.randn(n_time, n_trials) * 5.0

            # Combine components
            signal = (
                base_sigma * gaussian_noise
                + 0.1 * drift
                + spikes
            )

            # Apply participant + electrode scaling
            signal *= (participant_gain * electrode_gain)

            # Store into main tensor
            data[:, :, ch, p] = signal.astype(np.float32)

    # ---- participant IDs ----
    participant_ids = np.arange(1, n_participants + 1, dtype=np.int32)

    # ---- ensure output directory exists ----
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # ---- save to .mat ----
    mat_dict = {
        "data": data,
        "labels": labels,
        "participant_ids": participant_ids,
        "fs": np.array([[fs]], dtype=np.int32),
        "trial_length_sec": np.array([[trial_length_sec]], dtype=np.int32),
    }

    savemat(out_path, mat_dict)
    print(f"Saved fake EEG data to: {out_path.resolve()}")


if __name__ == "__main__":
    generate_fake_eeg_mat()