# -*- coding: utf-8 -*-
"""dataloader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJmS-yZs1yQ2GzqPeptwsZw-Q4QyOTJY

This folder contains the function that takes the dictionary with the data "folds" from the splits folder, and the fold number "k", and outputs train_loader and test_loader for the rest of the code. **Remember to make a loop in front of the function in other code so it runs all the iterations, not just one fold validation. **
"""

import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader



def make_dataloaders(folds: dict, k: int, batch_size: int): #k is used so that in the scripts I can loop over this code and the training code 5 times with different test sets.
    """
    Given a folds dict and a chosen fold k, build DataLoaders where:
      - the selected fold is test/val
      - all other folds combined are training data

    Returns
    -------
    train_loader, test_loader
    """
    fold_key = f"fold_{k}"
    assert fold_key in folds, f"{fold_key} not found in folds."

    # --- test data comes entirely from the chosen fold ---
    test_data   = folds[fold_key]["data"]
    test_labels = folds[fold_key]["labels"]

    # --- training data is all other folds concatenated ---
    train_data_list = []
    train_label_list = []

    for this_key, fold in folds.items():
        if this_key == fold_key:
            continue
        train_data_list.append(fold["data"])
        train_label_list.append(fold["labels"])

    train_data   = np.concatenate(train_data_list, axis=0)
    train_labels = np.concatenate(train_label_list, axis=0)

    # --- convert to tensors ---
    train_X = torch.tensor(train_data, dtype=torch.float32)
    train_y = torch.tensor(train_labels, dtype=torch.long)

    test_X  = torch.tensor(test_data,  dtype=torch.float32)
    test_y  = torch.tensor(test_labels, dtype=torch.long)

    # --- datasets ---
    train_dataset = TensorDataset(train_X, train_y)
    test_dataset  = TensorDataset(test_X,  test_y)

    # --- dataloaders ---
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,   #get this from the DATA_HPARAM Dict. I hope..
        shuffle=True,
        drop_last=True,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=test_dataset.tensors[0].shape[0],
        shuffle=False,
    )

    return train_loader, test_loader