# -*- coding: utf-8 -*-
"""splits

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UsZy1At7oGVDJRMjoRnykTl8drYrb3I
"""

import numpy as np
import pandas as pd
import mne
from scipy.io import loadmat
from sklearn.model_selection import StratifiedGroupKFold


def load_eeg_and_triggers(
    eeg_file: str,
    window_size: int,
    overlap: float,
):
    """
    Loads trial-wise EEG from a .mat file and splits each 15s trial into smaller windows.

    Parameters
    ----------
    eeg_file : str
        Path to .mat file with variables:
          - data: (time, trial, electrode, participant)
          - labels: (trial, participant)
          - participant_ids: (participant,)
    trigger_csv : str
        Unused for .mat-based loading (kept for API compatibility).
    window_size : int
        Window size in samples.
    overlap : float
        Fraction overlap between consecutive windows (e.g. 0.5).

    Returns
    -------
    X : np.ndarray
        Shape (n_windows, n_channels, window_size)
    y : np.ndarray
        Shape (n_windows,)
    subjects : np.ndarray
        Shape (n_windows,)
    """

    # ---------- LOAD FROM .MAT ----------
    mat = loadmat(eeg_file)

    data = mat["data"]             # (time, trial, electrode, participant)
    labels = mat["labels"]         # (trial, participant)
    participant_ids = mat.get("participant_ids", None)

    n_time, n_trials, n_electrodes, n_participants = data.shape

    X_list = []
    y_list = []
    subjects_list = []

    step = int(window_size * (1 - overlap))

    # ---------- LOOP OVER PARTICIPANTS AND TRIALS ----------
    for p in range(n_participants):
        # subject ID for this participant
        if participant_ids is not None:
            subject_id = int(participant_ids.squeeze()[p])
        else:
            subject_id = p  # fallback

        for t in range(n_trials):
            # segment shape: (channels, time)
            segment = data[:, t, :, p].T
            trial_len = segment.shape[1]

            # label for trial t
            label = int(labels[t, p])

            # ---- Sliding window loop ----
            for s in range(0, trial_len - window_size + 1, step):
                window = segment[:, s : s + window_size]  # (n_channels, window_size)

                X_list.append(window)
                y_list.append(label)
                subjects_list.append(subject_id)

    # Convert to numpy arrays
    X = np.stack(X_list, axis=0)  # (n_windows, n_channels, window_size)
    y = np.asarray(y_list)
    subjects = np.asarray(subjects_list)

    assert len(X) == len(y) == len(subjects), "Mismatch between X, y, subjects."

    return X, y, subjects

def make_stratified_group_folds(
    X: np.ndarray,
    y: np.ndarray,
    groups: np.ndarray,
    n_splits: int = 5,
    random_state: int = 0,
):
    """
    Create stratified group k-fold splits and return a dict where each entry
    is just the data/labels/subjects belonging to that fold.

    folds["fold_0"]["data"]     -> X for that fold
    folds["fold_0"]["labels"]   -> y for that fold
    folds["fold_0"]["subjects"] -> groups for that fold
    """
    cv = StratifiedGroupKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=random_state,
    )

    folds = {}

    for fold_idx, (_, idx) in enumerate(cv.split(X, y, groups)):
        fold_key = f"fold_{fold_idx}"

        folds[fold_key] = {
            "data":     X[idx],
            "labels":   y[idx],
            "subjects": groups[idx],
        }

    return folds  #return K????

