# -*- coding: utf-8 -*-
"""train_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmg8ptyaZQ-iFKtGGi3hOlOa4b7fE1JI

This is where I store the first version of my training loop function. I will probably use this for all of my training.

so far the training function will take inputs:

*   model
*   train_loader
*   test_loader
*   num_epochs
*   learning_rate
*   betas
*   weight_decay

It then outputs:

*   model
*   train_loss
*   train_errors
*   test_loss
*   test_errors
"""

import torch
import torch.nn as nn
from typing import Dict, Tuple

def train_GUTNet(
    model: nn.Module,
    train_loader,
    test_loader,
    TRAINING_HPARAMS: Dict,
    device: torch.device,
):
    """
    Train a classification model with Adam + CrossEntropyLoss.

    Parameters
    ----------
    model : torch.nn.Module
        Your CNN (or other) model.
    train_loader : DataLoader
        DataLoader for training data.
    test_loader : DataLoader
        DataLoader for test/validation data.
    TRAINING_HPARAMS : Dict
        Dictionary containing training hyperparameters:
      num_epochs : int
          Number of epochs to train.
      learning_rate : float
          Learning rate for Adam.
      betas : tuple
          Betas for Adam optimizer, e.g. (0.5, 0.999).
      weight_decay : float
          L2 weight decay parameter for Adam.

    Returns
    -------
    model : torch.nn.Module
        The trained model (updated in-place).
    train_losses : list[float]
        Average training loss per epoch.
    train_errors : list[float]
        Average training error rate (0–1) per epoch.
    test_losses : list[float]
        Average test loss per epoch.
    test_errors : list[float]
        Average test error rate (0–1) per epoch.
    """
# --- unpack hyperparameters from dict ---
    learning_rate = TRAINING_HPARAMS["learning_rate"]
    num_epochs    = TRAINING_HPARAMS["num_epochs"]
    betas         = TRAINING_HPARAMS.get("betas", (0.9, 0.999))
    weight_decay  = TRAINING_HPARAMS.get("weight_decay", 0.0)

    # --- loss function ---
    criterion = nn.CrossEntropyLoss().to(device)

    # --- optimizer ---
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=learning_rate,
        betas=betas,
        weight_decay=weight_decay,
    )


    # To store metrics for each epoch
    train_losses = []
    train_errors = []
    test_losses = []
    test_errors = []

    for epoch in range(num_epochs):
        # ----- TRAINING LOOP -----
        model.train()
        running_loss = 0.0
        running_errors = 0
        n_train_samples = 0

        for inputs, targets in train_loader:
            inputs = inputs.to(device)
            targets = targets.to(device)  # assumed to be class indices: 0..C-1

            # Forward pass
            outputs = model(inputs)  # shape: (batch_size, num_classes)
            loss = criterion(outputs, targets)

            # Backward + update
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Bookkeeping
            batch_size = inputs.size(0)
            running_loss += loss.item() * batch_size  # sum over samples

            # Classification error = proportion of wrong predictions
            preds = outputs.argmax(dim=1)
            batch_errors = (preds != targets).sum().item()
            running_errors += batch_errors
            n_train_samples += batch_size

        # Average across all training samples (equivalent to batch-averaged)
        avg_train_loss = running_loss / n_train_samples
        avg_train_error = running_errors / n_train_samples

        train_losses.append(avg_train_loss)
        train_errors.append(avg_train_error)

        # ----- TEST / EVAL LOOP -----
        model.eval()
        test_running_loss = 0.0
        test_running_errors = 0
        n_test_samples = 0

        with torch.no_grad():
            for inputs, targets in test_loader:
                inputs = inputs.to(device)
                targets = targets.to(device)

                outputs = model(inputs)
                loss = criterion(outputs, targets)

                batch_size = inputs.size(0)
                test_running_loss += loss.item() * batch_size

                preds = outputs.argmax(dim=1)
                batch_errors = (preds != targets).sum().item()
                test_running_errors += batch_errors
                n_test_samples += batch_size

        avg_test_loss = test_running_loss / n_test_samples
        avg_test_error = test_running_errors / n_test_samples

        test_losses.append(avg_test_loss)
        test_errors.append(avg_test_error)

        # print progress
        print(
            f"Epoch [{epoch+1}/{num_epochs}] "
            f"Train loss: {avg_train_loss:.4f}, Train error: {avg_train_error:.4f} "
            f"| Test loss: {avg_test_loss:.4f}, Test error: {avg_test_error:.4f}"
        )

    return model, train_losses, train_errors, test_losses, test_errors