# -*- coding: utf-8 -*-
"""classifier_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIPxqEb4SMEkiP6EABBgzI9xbXb85nlG

Okey, so this is the vanilla ass fully connected classifier head of the model. It takes inputs:
*   conv3_output_channels
*   class_dropout
*   linear1_hidden_size
*   activation_fn

I am fairly suspisious of how simple this looks, but if it works I wouldn't complain.
"""

import torch.nn as nn

class Classifier(nn.Module):
    def __init__(self,
                 conv3_output_channels,   # input feature size = output of CNN
                 class_dropout,
                 linear1_hidden_size,
                 activation_fn):
        super().__init__()
        self.activation = self._get_activation(activation_fn)

        # ----------------------------
        # fully-connected head
        # ----------------------------
        self.fc1 = nn.Linear(conv3_output_channels, linear1_hidden_size)

        self.dropout = nn.Dropout(p=class_dropout)

        # output dimension = 3 classes for emotion classification
        self.fc_out = nn.Linear(linear1_hidden_size, 3)

    def _get_activation(self, name: str):
        name = name.lower()
        if name == "relu":
            return nn.ReLU()
        elif name == "gelu":
            return nn.GELU()
        elif name == "leakyrelu":
            return nn.LeakyReLU()
        else:
            raise ValueError(f"Unknown activation_fn: {name}")

    def forward(self, x):
        # x: (batch, conv3_output_channels)
        x = self.fc1(x)
        x = self.activation(x)
        x = self.dropout(x)
        x = self.fc_out(x)
        return x