# -*- coding: utf-8 -*-
"""cnn_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19aUMVU6xduuuD4qlvFnvn0lgRfCMohRO

In this file I will make the function that creates the cnn model class. This will be the model architecture of the ccn part of the model.
Takes inputs:

*   conv1_hidden_channels
*   conv2_hidden_channels
*   conv3_output_channels
*   conv1_kernel_size
*   conv2_kernel_size
*   conv3_kernel_size
*   conv1_stride
*   conv2_stride
*   conv3_stride
*   maxpool_ks
*   conv_dropout
*   activation_fn

(well fuck that is alot)

Outputs:
x = feature tenor
"""

import torch.nn as nn

class cnnNet(nn.Module):
    def __init__(self,
                 conv1_hidden_channels,
                 conv2_hidden_channels,
                 conv3_output_channels,
                 conv1_kernel_size,
                 conv2_kernel_size,
                 conv3_kernel_size,
                 conv1_stride,
                 conv2_stride,
                 conv3_stride,
                 maxpool_ks,
                 conv_dropout,
                 activation_fn
                 ):
        super().__init__()

        # Convert activation function string → actual nn.Module
        self.activation = self._get_activation(activation_fn)

        # ------------------
        # CONV 1 BLOCK
        # ------------------
        self.conv1 = nn.Conv1d(
            in_channels=20,
            out_channels=conv1_hidden_channels,
            kernel_size=conv1_kernel_size,
            stride=conv1_stride,
            padding="same"
        )
        self.bn1 = nn.BatchNorm1d(conv1_hidden_channels)
        self.dropout1 = nn.Dropout(conv_dropout)
        self.pool1 = nn.MaxPool1d(maxpool_ks)

        # ------------------
        # CONV 2 BLOCK
        # ------------------
        self.conv2 = nn.Conv1d(
            in_channels=conv1_hidden_channels,
            out_channels=conv2_hidden_channels,
            kernel_size=conv2_kernel_size,
            stride=conv2_stride,
            padding="same"
        )
        self.bn2 = nn.BatchNorm1d(conv2_hidden_channels)
        self.dropout2 = nn.Dropout(conv_dropout)
        self.pool2 = nn.MaxPool1d(maxpool_ks)

        # ------------------
        # CONV 3 BLOCK
        # ------------------
        self.conv3 = nn.Conv1d(
            in_channels=conv2_hidden_channels,
            out_channels=conv3_output_channels,
            kernel_size=conv3_kernel_size,
            stride=conv3_stride,
            padding="same"
        )
        self.bn3 = nn.BatchNorm1d(conv3_output_channels)
        self.dropout3 = nn.Dropout(conv_dropout)
        self.pool3 = nn.MaxPool1d(maxpool_ks)

    # Activation function selector
    def _get_activation(self, name: str):
        name = name.lower()
        if name == "relu":
            return nn.ReLU()
        elif name == "gelu":
            return nn.GELU()
        elif name == "leakyrelu":
            return nn.LeakyReLU()
        else:
            raise ValueError(f"Unknown activation_fn: {name}")

    def forward(self, x):

        # ---- Block 1 ----
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.activation
        x = self.pool1(x)
        x = self.dropout1(x)

        # ---- Block 2 ----
        x = self.conv2(x)
        x = self.bn2(x)
        x = self.activation
        x = self.pool2(x)
        x = self.dropout2(x)

        # ---- Block 3 ----
        x = self.conv3(x)
        x = self.bn3(x)
        x = self.activation
        x = self.pool3(x)
        x = self.dropout3(x)

        return x

