# -*- coding: utf-8 -*-
"""cnn_classifier_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zE31lWBn0SVOzl2emZH7GoPqPdXMMeGy

This is the combined model between my cnn architecture and my classifier architecture. I am trying to use a lego building blocks approch to this project so that the parts will be easier to interchange later. My only problem with this will be the hyperparameters, as they are fucking hard to keep track of when you interchange models alot...

anyway, this model inputs:
*   conv1_hidden_channels
*   conv2_hidden_channels
*   conv3_output-channels
*   conv1_kernel_size
*   conv2_kernel_size
*   conv3_kernel_size
*   conv1_stride
*   conv2_stride
*   conv3_stride
*   maxpool_ks
*   conv_dropout
*   class_dropout
*   linear1_hidden_size
*   activation_fn

It outputs x
"""

import torch.nn as nn
from .cnn_model import cnnNet
from .classifier_model import Classifier


class GUTNet(nn.Module):
    def __init__(self,
                 conv1_hidden_channels,
                 conv2_hidden_channels,
                 conv3_output_channels,
                 conv1_kernel_size,
                 conv2_kernel_size,
                 conv3_kernel_size,
                 conv1_stride,
                 conv2_stride,
                 conv3_stride,
                 maxpool_ks,
                 conv_dropout,
                 class_dropout,
                 linear1_hidden_size,
                 activation_fn):
        super().__init__()

        # CNN feature extractor
        self.cnn = cnnNet(
            conv1_hidden_channels=conv1_hidden_channels,
            conv2_hidden_channels=conv2_hidden_channels,
            conv3_output_channels=conv3_output_channels,
            conv1_kernel_size=conv1_kernel_size,
            conv2_kernel_size=conv2_kernel_size,
            conv3_kernel_size=conv3_kernel_size,
            conv1_stride=conv1_stride,
            conv2_stride=conv2_stride,
            conv3_stride=conv3_stride,
            maxpool_ks=maxpool_ks,
            conv_dropout=conv_dropout,
            activation_fn=activation_fn,
        )

        # Classifier head
        self.head = Classifier(
            conv3_output_channels=conv3_output_channels,
            class_dropout=class_dropout,
            linear1_hidden_size=linear1_hidden_size,
            activation_fn=activation_fn,
        )

    def forward(self, x):
        # x: (batch, channels=20, time)
        x = self.cnn(x)        # -> (batch, conv3_output_channels, time_reduced)

        # global average pooling over time dimension
        x = x.mean(dim=-1)     # -> (batch, conv3_output_channels)

        x = self.head(x)       # -> (batch, num_classes=3)
        return x